default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: rails_user
  password:

development:
  <<: *default
  database: manyo_development

test:
  <<: *default
  database: manyo_test

production:
  <<: *default
  database: manyo_production
